-- EJERCICIO BD ALUMNOS

-- CREAR UNA TABLA LLAMADA TUTORES
-- LA TABLA DEBE LLEVAR LAS SIGUIENTES COLUMNAS
-- TUTOR_ID (PRIMARY KEY)
-- NOMBRE
-- CLAVE DEL TUTOR (QUE ESTA CLAVE SOLO PUEDAN SER LAS LETRAS A, B, C D)
-- INSERTAN POR LO MENOS 3 REGISTROS DE TUTORES

-- CREAR UNA TABLA RELACIONAL LLAMADA TUTORES_ALUMNOS
-- DEBE LLEVAR SU PROPIA COLUMNA CON PRIMARY KEY (ID_TA)
-- ID_TUTOR
-- ID_ALUMNO
-- CREAN LAS RESPECTIVAS LLAVES FORANEAS PARA RECIBIR LA INFO
-- PROVENIENTE DE ALUMNO_ID Y TUTOR_ID
-- INSERTAN 3 REGISTROS PARE RELACIONAR QUE TUTOR
-- LE DA ASESORÍA/CLASES A QUÉ ALUMNO


-- CREAR UNA TABLA LLAMADA TUTORES
-- LA TABLA DEBE LLEVAR LAS SIGUIENTES COLUMNAS
-- TUTOR_ID (PRIMARY KEY)
-- NOMBRE
-- CLAVE DEL TUTOR (QUE ESTA CLAVE SOLO PUEDAN SER LAS LETRAS A, B, C D)

DROP TABLE TUTORES;
-- EJEMPLO DE LA CREACION DE LA TABLA TUTORES, CON LAS RESTRICCIONES CREADAS
-- DESDE UN INICIO (CHECK)

CREATE TABLE TUTORES(
TUTOR_ID NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(30),
CLAVE NVARCHAR2(1),
CONSTRAINT CHK_CLAVE_TUTOR CHECK (CLAVE IN('A','B','C','D'))
);

INSERT INTO TUTORES VALUES (1,'JINGER','A');
INSERT INTO TUTORES VALUES (2,'BLOSON','B');
INSERT INTO TUTORES VALUES (3,'ALISSA','C');
INSERT INTO TUTORES VALUES (4,'WHITE','D');

SELECT * FROM TUTORES;

-- EJEMPLO DE CREAR LA TABLA TUTORES_ALUMNOS CON SUS RESTRICCIONES DE LLAVES FORANEAS
-- CREADAS AL INICIO DE LA TABLA

CREATE TABLE TUTORES_ALUMNOS(
TA_ID NUMBER PRIMARY KEY,
TUTOR_ID NUMBER,
ALUMNO_ID NUMBER,
CONSTRAINT FK_TUTOR_ID_TA FOREIGN KEY (TUTOR_ID) REFERENCES TUTORES (TUTOR_ID),
CONSTRAINT FK_ALUMNO_ID_TA FOREIGN KEY (ALUMNO_ID) REFERENCES ALUMNOS (ALUMNO_ID)
);

-- REGISTROS DE TUTORES Y ALUMNOS 
INSERT INTO TUTORES_ALUMNOS VALUES (1, 3, 7);
INSERT INTO TUTORES_ALUMNOS VALUES (2, 4, 2);
INSERT INTO TUTORES_ALUMNOS VALUES (3, 1, 3);
SELECT * FROM TUTORES_ALUMNOS;

/*
CREATE TABLE TUTORES(
TUTOR_ID NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(30),
CLAVE NVARCHAR2(1)
);

ALTER TABLE TUTORES ADD CONSTRAINT CHK_CLAVE
CHECK (CLAVE IN('A','B','C','D'));


-- INSERTAN POR LO MENOS 3 REGISTROS DE TUTORES

INSERT INTO TUTORES VALUES(1, 'ANSELMO', 'A');
INSERT INTO TUTORES VALUES(2, 'ALIZA', 'B');
INSERT INTO TUTORES VALUES(3, 'JINJER', 'C');

SELECT * FROM tutores;
COMMIT;*/

-- CREAR UNA TABLA RELACIONAL LLAMADA TUTORES_ALUMNOS
-- DEBE LLEVAR SU PROPIA COLUMNA CON PRIMARY KEY (ID_TA)
-- ID_TUTOR
-- ID_ALUMNO
-- CREAN LAS RESPECTIVAS LLAVES FORANEAS PARA RECIBIR LA INFO
-- PROVENIENTE DE ALUMNO_ID Y TUTOR_ID
-- INSERTAN 3 REGISTROS PARA RELACIONAR QUE TUTOR
-- LE DA ASESORÍA/CLASES A QUÉ ALUMNO
